version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        RUBY_VERSION: '${RUBY_VERSION:-3.0}'
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - DATABASE_URL=postgres://postgres:password@db/
      - SMTP_URL=smtp://smtp:1025
    ports:
      - 3000:3000
    volumes:
      - ./:/alaveteli
      - ../alaveteli-themes:/alaveteli-themes
      - bundle:/bundle
    depends_on:
      - db
      - smtp

  db:
    build:
      context: .
      dockerfile: docker/Dockerfile-postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 6432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  smtp:
    image: mailhog/mailhog
    ports:
      - 1080:8025

volumes:
  bundle: {}
  postgres: {}
