version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        RUBY_VERSION: '${RUBY_VERSION:-3.0}'
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - DATABASE_URL=postgres://postgres:password@db/
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
      - 1080:1080
    volumes:
      - ./:/alaveteli
      - ../alaveteli-themes:/alaveteli-themes
      - bundle:/bundle
    depends_on:
      - db
      - redis

  sidekiq:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        RUBY_VERSION: '${RUBY_VERSION:-3.0}'
    command: bundle exec sidekiq
    volumes:
      - ./:/alaveteli
      - ../alaveteli-themes:/alaveteli-themes
      - bundle:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - DATABASE_URL=postgres://postgres:password@db/
      - REDIS_URL=redis://redis:6379
    depends_on:
      - 'db'
      - 'redis'

  db:
    build:
      context: .
      dockerfile: docker/Dockerfile-postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 6432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: library/redis
    command: redis-server
    volumes:
      - redis:/data

volumes:
  bundle: {}
  postgres: {}
  redis: {}
